:_module-type: PROCEDURE

[id='guardrails-orchestrator-optional-config-OTEL_{context}']

= Configuring the OpenTelemetry Exporter for metrics and tracing

[role='_abstract']
Enable traces and metrics that are provided for the observability of the `GuardrailsOrchestrator` service with the OpenTelemetry Operator.

.Prerequisites
* Install the Red Hat OpenShift distributed tracing platform from the OperatorHub. Create a Jaeger instance using the default settings.
* Install the Red Hat build of OpenTelemetry from the OperatorHub. Create an OpenTelemetry instance

.Procedure
. Define a `GuardrailsOrchestrator` custom resource object in a yaml file called `orchestrator_otel_cr.yaml` which specifies the `otelExporter` configurations:

.Example of a `orchestrator_otel_cr.yaml` object that has OpenTelemetry configured:
+
[source,yaml]
---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: gorch-test
spec:
  replicas: 1
  otelExporter:
    protocol: "http"
    otlpEndpoint: "localhost:4318"
    otlpExport: "metrics"
---

. Deploy the orchestrator custom resource.
[source,terminal]
---
$ oc apply -f orchestrator_otel_cr.yaml
---